version: '3.7'
services:

    # Web Service (see dockerfile)
    web:
        build:
            context: .
            target: web
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on: #create db, then redis container first
            - db
            - redis

    # Database Server
    db:
        image: mysql:5.7
        ports:
            - '3306:3306'
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql

    # Redis Server
    redis:
        image: redis:alpine
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        ports:
            - 6379:6379


volumes:
    db-data: ~
